"use server";

import { supabase } from "@/lib/supabase";

export const getTeachers = async () => {
  // return teachers;
  const { data, error } = await supabase
    .from('teachers')
    .select(`
      id,
      first_name,
      last_name,
      department,
      email,
      highest_qualification
    `);


  if (error) {
    console.error("Error fetching teachers:", error);
    return [];
  }
  return data;
}


const teachers = [
  {
    t_id: 1,
    name: "Aarav Sharma",
    department_id: 101,
    email: "aarav.sharma@example.com",
    qualification: "Ph.D.",
  },
  {
    t_id: 2,
    name: "Neha Verma",
    department_id: 101,
    email: "neha.verma@example.com",
    qualification: "M.Tech",
  },
  {
    t_id: 3,
    name: "Rahul Patel",
    department_id: 101,
    email: "rahul.patel@example.com",
    qualification: "M.Tech",
  },
  {
    t_id: 4,
    name: "Sneha Singh",
    department_id: 102,
    email: "sneha.singh@example.com",
    qualification: "Ph.D.",
  },
  {
    t_id: 5,
    name: "Vikram Mehta",
    department_id: 102,
    email: "vikram.mehta@example.com",
    qualification: "M.E.",
  },
  {
    t_id: 6,
    name: "Pooja Nair",
    department_id: 102,
    email: "pooja.nair@example.com",
    qualification: "M.Tech",
  },
  {
    t_id: 7,
    name: "Rohan Desai",
    department_id: 103,
    email: "rohan.desai@example.com",
    qualification: "Ph.D.",
  },
  {
    t_id: 8,
    name: "Isha Reddy",
    department_id: 103,
    email: "isha.reddy@example.com",
    qualification: "M.Tech",
  },
  {
    t_id: 9,
    name: "Ajay Joshi",
    department_id: 103,
    email: "ajay.joshi@example.com",
    qualification: "M.E.",
  },
  {
    t_id: 10,
    name: "Kiran Thakur",
    department_id: 104,
    email: "kiran.thakur@example.com",
    qualification: "Ph.D.",
  },
  {
    t_id: 11,
    name: "Deepak Kapoor",
    department_id: 104,
    email: "deepak.kapoor@example.com",
    qualification: "M.Tech",
  },
  {
    t_id: 12,
    name: "Anjali Shah",
    department_id: 104,
    email: "anjali.shah@example.com",
    qualification: "M.E.",
  },
  {
    t_id: 13,
    name: "Siddharth Kulkarni",
    department_id: 105,
    email: "siddharth.k@example.com",
    qualification: "Ph.D.",
  },
  {
    t_id: 14,
    name: "Tanvi Mishra",
    department_id: 105,
    email: "tanvi.mishra@example.com",
    qualification: "M.Tech",
  },
  {
    t_id: 15,
    name: "Harsh Garg",
    department_id: 105,
    email: "harsh.garg@example.com",
    qualification: "M.Tech",
  },
  {
    t_id: 16,
    name: "Ritika Chopra",
    department_id: 101,
    email: "ritika.chopra@example.com",
    qualification: "Ph.D.",
  },
  {
    t_id: 17,
    name: "Aditya Malhotra",
    department_id: 101,
    email: "aditya.m@example.com",
    qualification: "M.E.",
  },
  {
    t_id: 18,
    name: "Meera Yadav",
    department_id: 101,
    email: "meera.yadav@example.com",
    qualification: "Ph.D.",
  },
  {
    t_id: 19,
    name: "Amit Choudhary",
    department_id: 102,
    email: "amit.choudhary@example.com",
    qualification: "Ph.D.",
  },
  {
    t_id: 20,
    name: "Swati Agarwal",
    department_id: 102,
    email: "swati.agarwal@example.com",
    qualification: "M.Sc.",
  },
  {
    t_id: 21,
    name: "Manoj Dwivedi",
    department_id: 102,
    email: "manoj.dwivedi@example.com",
    qualification: "Ph.D.",
  },
  {
    t_id: 22,
    name: "Bhavna Pathak",
    department_id: 103,
    email: "bhavna.pathak@example.com",
    qualification: "M.Tech",
  },
  {
    t_id: 23,
    name: "Sandeep Bajpai",
    department_id: 103,
    email: "sandeep.bajpai@example.com",
    qualification: "Ph.D.",
  },
  {
    t_id: 24,
    name: "Shweta Pandey",
    department_id: 103,
    email: "shweta.pandey@example.com",
    qualification: "Ph.D.",
  },
  {
    t_id: 25,
    name: "Vinay Tiwari",
    department_id: 104,
    email: "vinay.tiwari@example.com",
    qualification: "M.Tech",
  },
  {
    t_id: 26,
    name: "Divya Srivastava",
    department_id: 104,
    email: "divya.sri@example.com",
    qualification: "Ph.D.",
  },
  {
    t_id: 27,
    name: "Raj Chaudhary",
    department_id: 104,
    email: "raj.chaudhary@example.com",
    qualification: "Ph.D.",
  },
  {
    t_id: 28,
    name: "Nikita Joshi",
    department_id: 105,
    email: "nikita.joshi@example.com",
    qualification: "M.Sc.",
  },
  {
    t_id: 29,
    name: "Saurabh Gupta",
    department_id: 105,
    email: "saurabh.gupta@example.com",
    qualification: "Ph.D.",
  },
  {
    t_id: 30,
    name: "Preeti Kale",
    department_id: 105,
    email: "preeti.kale@example.com",
    qualification: "M.Tech",
  },
  {
    t_id: 31,
    name: "Abhinav Rawat",
    department_id: 101,
    email: "abhinav.rawat@example.com",
    qualification: "Ph.D.",
  },
  {
    t_id: 32,
    name: "Priya Shetty",
    department_id: 101,
    email: "priya.shetty@example.com",
    qualification: "M.E.",
  },
  {
    t_id: 33,
    name: "Aakash Banerjee",
    department_id: 101,
    email: "aakash.banerjee@example.com",
    qualification: "Ph.D.",
  },
  {
    t_id: 34,
    name: "Kavita Tripathi",
    department_id: 101,
    email: "kavita.tripathi@example.com",
    qualification: "M.Tech",
  },
  {
    t_id: 35,
    name: "Sameer Gokhale",
    department_id: 102,
    email: "sameer.gokhale@example.com",
    qualification: "Ph.D.",
  },
  {
    t_id: 36,
    name: "Manisha Deshmukh",
    department_id: 102,
    email: "manisha.deshmukh@example.com",
    qualification: "M.Tech",
  },
  {
    t_id: 37,
    name: "Rajesh Bhosale",
    department_id: 102,
    email: "rajesh.bhosale@example.com",
    qualification: "Ph.D.",
  },
  {
    t_id: 38,
    name: "Anusha Iyer",
    department_id: 102,
    email: "anusha.iyer@example.com",
    qualification: "Ph.D.",
  },
  {
    t_id: 39,
    name: "Yash Salunkhe",
    department_id: 103,
    email: "yash.salunkhe@example.com",
    qualification: "M.Tech",
  },
  {
    t_id: 40,
    name: "Payal Sawant",
    department_id: 103,
    email: "payal.sawant@example.com",
    qualification: "M.E.",
  },
  {
    t_id: 41,
    name: "Nikhil Bhagat",
    department_id: 103,
    email: "nikhil.bhagat@example.com",
    qualification: "Ph.D.",
  },
  {
    t_id: 42,
    name: "Trisha Kulshreshtha",
    department_id: 103,
    email: "trisha.kul@example.com",
    qualification: "M.Tech",
  },
  {
    t_id: 43,
    name: "Kunal Thombre",
    department_id: 104,
    email: "kunal.thombre@example.com",
    qualification: "Ph.D.",
  },
  {
    t_id: 44,
    name: "Pallavi Jagtap",
    department_id: 104,
    email: "pallavi.jagtap@example.com",
    qualification: "M.Sc.",
  },
  {
    t_id: 45,
    name: "Suresh Waghmare",
    department_id: 104,
    email: "suresh.waghmare@example.com",
    qualification: "Ph.D.",
  },
  {
    t_id: 46,
    name: "Radhika Naik",
    department_id: 104,
    email: "radhika.naik@example.com",
    qualification: "Ph.D.",
  },
  {
    t_id: 47,
    name: "Tushar Bhandari",
    department_id: 105,
    email: "tushar.bhandari@example.com",
    qualification: "M.Tech",
  },
  {
    t_id: 48,
    name: "Shalini Bora",
    department_id: 105,
    email: "shalini.bora@example.com",
    qualification: "M.Tech",
  },
  {
    t_id: 49,
    name: "Mohit Rathore",
    department_id: 105,
    email: "mohit.rathore@example.com",
    qualification: "Ph.D.",
  },
  {
    t_id: 50,
    name: "Garima Kashyap",
    department_id: 105,
    email: "garima.kashyap@example.com",
    qualification: "M.Tech",
  },
];
