export const recentLectures = [
  {
    id: 1,
    course_name: "LDAM",
    class_name: "CS-K",
    timeslot: "10-11",
    date: "2025-04-12",
    attendance_marked: false,
  },
  {
    id: 2,
    course_name: "MATH101",
    class_name: "MA-A",
    timeslot: "9-10",
    date: "2025-04-13",
    attendance_marked: true,
  },
  {
    id: 3,
    course_name: "PHY102",
    class_name: "PH-B",
    timeslot: "8-9",
    date: "2025-04-14",
    attendance_marked: false,
  },
  {
    id: 4,
    course_name: "CHEM110",
    class_name: "CH-C",
    timeslot: "11-12",
    date: "2025-04-15",
    attendance_marked: true,
  },
  {
    id: 5,
    course_name: "BIO105",
    class_name: "BI-D",
    timeslot: "1-2",
    date: "2025-04-16",
    attendance_marked: false,
  },
];
